version: '3.3'
services:
  my-app:
    image: 192.168.99.100:5000/my-app:latest
    networks:
      - default
      - proxy
    ports:
      - "8888:8080"
    environment:
      - APP_ENV=dev
    secrets:
      - mysql.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/index"]
      interval: 1m
      timeout: 10s
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:1.17.6
    ports:
      - "80:80"
    configs:
    - source: nginx.conf
      target: /etc/nginx/nginx.conf
      mode: 0440
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: on-failure

secrets:
  mysql.env:
    external: true
networks:
  default:
  proxy:

configs:
  nginx.conf:
    file: ./nginx.conf
