version: '3.3'
services:
  my-app:
    image: 192.168.99.100:5000/my-app:latest
    networks:
      - default
      - proxy
    ports:
      - "8888:8080"
    environment:
      - APP_ENV=prod
    secrets:
      - mysql.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 1m
      timeout: 10s
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: on-failure

secrets:
  mysql.env:
    external: true
networks:
  default:
  proxy:
